import express from 'express';
import sessionsApi from './sessions';
import usersApi from './users';
import messagesApi from './messages';
import bookApi from './book';
import renewApi from './renews';
import bookdetailApi from './book-detail';
import researchDirections from './researchDirections';
import home from './home';
import notice from './notice';
import postgraduateTraining from './postgraduateTraining';
import productPrototype from './productPrototype';
import researchProjects from './researchProjects';
import teamMembers from './teamMembers';
const router = express.Router();
router.use('/sessions', sessionsApi);
router.use('/researchDirections', researchDirections);
router.use('/home', home);
router.use('/notice', notice);
router.use('/postgraduateTraining', postgraduateTraining);
router.use('/productPrototype', productPrototype);
router.use('/researchProjects', researchProjects);
router.use('/teamMembers', teamMembers);
router.use('/users', usersApi);
router.use('/messages', messagesApi);
router.use('/users/current/books/borrowed', bookApi);
router.use('/users/books/renew', renewApi);
router.use('/users/current/books/book-detail', bookdetailApi);
export default router;
