import express from 'express';
import researchDirections from './researchDirections';
import home from './home';
import notice from './notice';
import postgraduateTraining from './postgraduateTraining';
import productPrototype from './productPrototype';
import researchProjects from './researchProjects';
import teamMembers from './teamMembers';
const router = express.Router();
router.use('/researchDirections', researchDirections);
router.use('/home', home);
router.use('/notice', notice);
router.use('/postgraduateTraining', postgraduateTraining);
router.use('/productPrototype', productPrototype);
router.use('/researchProjects', researchProjects);
router.use('/teamMembers', teamMembers);
export default router;
